dataset :
  category_file_path : ./category_files/mg22_o16.json
  partial_cloud_path : ../data/%s/partial/%s/%s.npy
  gt_cloud_path : ../data/%s/complete/%s.npy
  n_points : 2048
  train : { partial : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/512c/384p/filtered_mg-o_partial_train.npy,
            complete : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/512c/filtered_mg-o_complete_train.npy
          }
  val   : { partial : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/512c/384p/filtered_mg-o_partial_val.npy,
            complete : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/512c/filtered_mg-o_complete_val.npy
          }
  test  : { partial : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/512c/384p/filtered_mg-o_partial_test.npy,
            complete : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/512c/filtered_mg-o_complete_test.npy
          }


optimizer : {
  type: Adam,
  kwargs: {
  lr : 0.0005 
  # weight_decay : 0
  }
}


scheduler: {
  type: StepLR,
  kwargs: {
    step_size: 100,
    gamma : 0.5
  }
}
            
model : 
  dim_feat: 512 
  num_pc: 256
  num_p0: 512
  radius: 1.0
  up_factors: [1, 2, 2]
  bounding : True


batch_size : 64
include_q : True
include_o : False
num_workers : 4
step_per_update: 1
epochs : 5000
save_freq : 20
loss_func : cd_l1
gpu : [0]
seed : 2024

RANGES : {
  MIN_X : -270.0,
  MAX_X : 270.0,
  MIN_Y : -270.0,
  MAX_Y : 270.0,
  MIN_Z : -185.0,
  MAX_Z : 1155.0, 
  MIN_Q : 1.0,
  MAX_Q : 10.2
}