dataset :
  category_file_path : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/variable_length/category_file.json
  partial_cloud_path : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/variable_length/%s/partial/%s/%s.npy
  gt_cloud_path : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/variable_length/%s/complete/%s.npy
  n_points : 2048
  train : { partial : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/512c/384p/Mg_O_combo_train_feats.npy,
            complete : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/512c/Mg_O_combo_train_labels.npy
          }
  val   : { partial : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/512c/384p/Mg_O_combo_val_feats.npy,
            complete : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/512c/Mg_O_combo_val_labels.npy
          }
  test  : { partial : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/512c/384p/Mg_O_combo_test_feats.npy,
            complete : /home/DAVIDSON/bewagner/data/22Mg_16O_combo/simulated/512c/Mg_O_combo_test_labels.npy
          }


optimizer : {
  type: Adam,
  kwargs: {
  # lr : 0.001, 
  # weight_decay : 0
  }
}


scheduler: {
  type: StepLR,
  kwargs: {
    step_size: 150,
    gamma : 0.1
  }
}
            
model : 
  dim_feat: 512 
  num_pc: 256
  num_p0: 512
  radius: 1.0
  up_factors: [1, 2, 2]
  bounding : True


batch_size : 32
include_q : True
num_workers : 4
step_per_update: 1
epochs : 5000
save_freq : 20
loss_func : emd4d
gpu : [0]
seed : 2024

RANGES : {
  MIN_X : -270.0,
  MAX_X : 270.0,
  MIN_Y : -270.0,
  MAX_Y : 270.0,
  MIN_Z : -185.0,
  MAX_Z : 1155.0, 
  MIN_Q : 1.0,
  MAX_Q : 10.2
}